# Generated by Django 5.0.2 on 2024-04-09 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_status', models.CharField(choices=[('unassigned', 'unassigned'), ('assigned', 'assigned'), ('in progress', 'in progress'), ('completed', 'completed')], max_length=100)),
                ('feedback', models.TextField(blank=True)),
                ('assigned_staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_schedule.taskfunnel')),
            ],
        ),
    ]
