# Generated by Django 5.0.2 on 2024-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0005_taskfunnel_assigned_staff_id_taskfunnel_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfunnel',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='taskfunnel',
            name='task_dept',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('HVAC', 'HVAC')], max_length=54),
        ),
    ]
