# Generated by Django 5.0.2 on 2024-05-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0006_remove_taskfunnel_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfunnel',
            name='scheduled_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
