# Generated by Django 5.0.2 on 2024-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0007_alter_taskfunnel_scheduled_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfunnel',
            name='task_num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
