# Generated by Django 5.0.2 on 2024-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0010_taskfunnel_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfunnel',
            name='feedback_url_status',
            field=models.BooleanField(default=True),
        ),
    ]
