# Generated by Django 5.0.2 on 2024-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0011_taskfunnel_feedback_url_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfunnel',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='Mid', max_length=54, null=True),
        ),
    ]
