# Generated by Django 5.0.2 on 2024-05-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0013_taskfunnel_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfunnel',
            name='feedback_sentiment',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], max_length=54, null=True),
        ),
    ]
