# Generated by Django 5.0.6 on 2024-07-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_schedule', '0014_taskfunnel_feedback_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfunnel',
            name='task_fault_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
