# Generated by Django 5.0.6 on 2024-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftschedule',
            name='assigned_staff_id',
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='assigned_staff_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='shift_day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
