# Generated by Django 5.0.6 on 2024-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_schedule', '0002_remove_shiftschedule_assigned_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_dept',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
