# Generated by Django 5.0.6 on 2024-06-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_schedule', '0003_shiftschedule_shift_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='start_time',
        ),
    ]
