# Generated by Django 5.0.2 on 2024-04-09 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('role', models.CharField(choices=[('Team Lead Mech', 'Team Lead Mech'), ('Team Lead Elect', 'Team Lead Elect'), ('Team Lead HVAC', 'Team Lead HVAC'), ('Ass Manager Mech', 'Ass Manager Mech'), ('Manager Mech', 'Manager Mech'), ('Manager HVAC', 'Manager HVAC'), ('Ass Manager HVAC', 'Ass Manager HVAC'), ('Manager Elect', 'Manager Elect'), ('Elect Technician', 'Elect Technician'), ('Mech Technician', 'Mech Technician'), ('HVAC Technician', 'HVAC Technician')], max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
