# Generated by Django 5.0.2 on 2024-04-09 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
