# Generated by Django 5.0.6 on 2024-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
